# Generated by Django 3.0.6 on 2020-07-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainusr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='discribtion',
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(max_length=200),
        ),
    ]
